/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as PickRouteImport } from './routes/pick'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamIdRouteImport } from './routes/team.$id'
import { Route as PickPlayersRouteImport } from './routes/pick/players'
import { Route as PickCaptainsRouteImport } from './routes/pick/captains'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const PickRoute = PickRouteImport.update({
  id: '/pick',
  path: '/pick',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIdRoute = TeamIdRouteImport.update({
  id: '/team/$id',
  path: '/team/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PickPlayersRoute = PickPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => PickRoute,
} as any)
const PickCaptainsRoute = PickCaptainsRouteImport.update({
  id: '/captains',
  path: '/captains',
  getParentRoute: () => PickRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/matches': typeof MatchesRoute
  '/pick': typeof PickRouteWithChildren
  '/teams': typeof TeamsRoute
  '/pick/captains': typeof PickCaptainsRoute
  '/pick/players': typeof PickPlayersRoute
  '/team/$id': typeof TeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/matches': typeof MatchesRoute
  '/pick': typeof PickRouteWithChildren
  '/teams': typeof TeamsRoute
  '/pick/captains': typeof PickCaptainsRoute
  '/pick/players': typeof PickPlayersRoute
  '/team/$id': typeof TeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/matches': typeof MatchesRoute
  '/pick': typeof PickRouteWithChildren
  '/teams': typeof TeamsRoute
  '/pick/captains': typeof PickCaptainsRoute
  '/pick/players': typeof PickPlayersRoute
  '/team/$id': typeof TeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/matches'
    | '/pick'
    | '/teams'
    | '/pick/captains'
    | '/pick/players'
    | '/team/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/matches'
    | '/pick'
    | '/teams'
    | '/pick/captains'
    | '/pick/players'
    | '/team/$id'
  id:
    | '__root__'
    | '/'
    | '/matches'
    | '/pick'
    | '/teams'
    | '/pick/captains'
    | '/pick/players'
    | '/team/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatchesRoute: typeof MatchesRoute
  PickRoute: typeof PickRouteWithChildren
  TeamsRoute: typeof TeamsRoute
  TeamIdRoute: typeof TeamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pick': {
      id: '/pick'
      path: '/pick'
      fullPath: '/pick'
      preLoaderRoute: typeof PickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$id': {
      id: '/team/$id'
      path: '/team/$id'
      fullPath: '/team/$id'
      preLoaderRoute: typeof TeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pick/players': {
      id: '/pick/players'
      path: '/players'
      fullPath: '/pick/players'
      preLoaderRoute: typeof PickPlayersRouteImport
      parentRoute: typeof PickRoute
    }
    '/pick/captains': {
      id: '/pick/captains'
      path: '/captains'
      fullPath: '/pick/captains'
      preLoaderRoute: typeof PickCaptainsRouteImport
      parentRoute: typeof PickRoute
    }
  }
}

interface PickRouteChildren {
  PickCaptainsRoute: typeof PickCaptainsRoute
  PickPlayersRoute: typeof PickPlayersRoute
}

const PickRouteChildren: PickRouteChildren = {
  PickCaptainsRoute: PickCaptainsRoute,
  PickPlayersRoute: PickPlayersRoute,
}

const PickRouteWithChildren = PickRoute._addFileChildren(PickRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatchesRoute: MatchesRoute,
  PickRoute: PickRouteWithChildren,
  TeamsRoute: TeamsRoute,
  TeamIdRoute: TeamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
